// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAS.ScrapingManagementService.Infrastructure.Persistence.AppDataContext;

#nullable disable

namespace SAS.ScrapingManagementService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531191135_FixScrapingtaskEntity")]
    partial class FixScrapingtaskEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.DataSources.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScrapingTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ScrapingTaskId");

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.DataSources.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6835f670-2e5c-8000-b5bb-ea9b1705cede"),
                            Description = "Telegram social media platform",
                            Name = "Telegram"
                        },
                        new
                        {
                            Id = new Guid("6835f670-2e5c-8000-b5bb-ea9b1705cedb"),
                            Description = "Twitter/X social media platform",
                            Name = "Twitter"
                        });
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.Scrapers.Entities.Scraper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScraperName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TasksHandled")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scrapers");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ScrapingDomains");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ScraperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("ScraperId");

                    b.ToTable("ScrapingTasks");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.DataSources.Entities.DataSource", b =>
                {
                    b.HasOne("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingDomain", "Domain")
                        .WithMany("DataSources")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAS.ScrapingManagementService.Domain.DataSources.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingTask", null)
                        .WithMany("DataSources")
                        .HasForeignKey("ScrapingTaskId");

                    b.Navigation("Domain");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingTask", b =>
                {
                    b.HasOne("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAS.ScrapingManagementService.Domain.Scrapers.Entities.Scraper", "ScrapingExecutor")
                        .WithMany()
                        .HasForeignKey("ScraperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Domain");

                    b.Navigation("ScrapingExecutor");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingDomain", b =>
                {
                    b.Navigation("DataSources");
                });

            modelBuilder.Entity("SAS.ScrapingManagementService.Domain.Scrapers.Entities.ScrapingTask", b =>
                {
                    b.Navigation("DataSources");
                });
#pragma warning restore 612, 618
        }
    }
}
